import { writeFileSync } from 'node:fs';
import { PLAYERS } from '../shared/src/players.ts';

const norm = (s: string) =>
  s.toLowerCase().normalize('NFD').replace(/[̀-ͯ]/g, '')
   .replace(/[.'`’]/g, '')
   .replace(/\b(jr|sr|ii|iii|iv|v)\b/g, '')
   .replace(/[^a-z0-9]+/g, ' ').trim();

async function main() {
  const teamsRes = await fetch('https://site.api.espn.com/apis/site/v2/sports/basketball/nba/teams');
  const teamsJson: any = await teamsRes.json();
  const teams = teamsJson.sports[0].leagues[0].teams.map((t: any) => t.team.abbreviation);
  console.log('ESPN teams:', teams.length);

  const nameToId: Record<string, string> = {};
  for (const abbr of teams) {
    try {
      const r = await fetch(`https://site.api.espn.com/apis/site/v2/sports/basketball/nba/teams/${abbr}/roster`);
      const j: any = await r.json();
      for (const a of j.athletes || []) {
        if (a.id && a.displayName) nameToId[norm(a.displayName)] = String(a.id);
      }
    } catch (e) { console.log('fail', abbr); }
  }
  console.log('ESPN athletes indexed:', Object.keys(nameToId).length);

  const map: Record<string, string> = {};
  const misses: string[] = [];
  for (const p of PLAYERS) {
    const id = nameToId[norm(p.name)];
    if (id) map[p.id] = id; else misses.push(p.name);
  }
  console.log(`Matched ${Object.keys(map).length}/${PLAYERS.length}; misses: ${misses.length}`);
  console.log('Miss sample:', misses.slice(0, 40).join(', '));

  const out = `// AUTO-GENERATED by scripts/build-player-images.mts — do not edit by hand.
// Maps player id -> ESPN athlete id for headshots.
export const PLAYER_ESPN_IDS: Record<string, string> = ${JSON.stringify(map, null, 0)};
`;
  writeFileSync('shared/src/playerImages.ts', out);
  console.log('Wrote shared/src/playerImages.ts');
}
main();
